### ISSUE TITLE
Finetuning Tacotron2 on your pretrained model

### ISSUE THREAD

**Issue by Mareike-RTY** [thorstenMueller/Thorsten-Voice#33]
Hello Thorsten,

first of all, thank you very much for providing such valuable voice data and resources! It's really impressive work that you have done.

Regarding my project: Working with TensorFlowTTS, I would like to finetune Tacotron2 with my own data on your pretained model which I took from [here](https://drive.google.com/drive/folders/1m4RuffbvdOmQWnmy_Hmw0cZ_q0hj2o8B). So far, I have only worked with pretrained models in .h5 format, which is probably why I'm struggling with getting your `data.pkl` file to "run". Somehow, I can't unpickle the `data.pkl` files (when loading it, I receive `_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.`). While doing some research, I came across [this](https://github.com/monatis/german-tts/blob/main/e2e-notebook.ipynb) notebook which downloads your models in the desired .h5 format. Unfortunately, the download links are no longer valid (404). 

Could you please point me into the right direction of how to use your model as pretrained model for finetuning? Any hint is very much appreciated. Thank you!

**Comment by thorstenMueller** [comment]
Thanks for your nice feedback on my work @Mareike-RTY .
Before you struggle on finetuning with existing Thorsten TTS-models maybe you want to wait some days until the new TTS-models will be released. We're in the final phase before release.

The new models will provide a much better and natural speech flow and for that might be a better startingpoint for your finetuning process.

Here you can hear the difference between "current" and "new" Thorsten model.
https://www.thorsten-voice.de/2022/03/20/vergleich-thorsten-aktuell-mit-dem-neuen-modell/

**Comment by Mareike-RTY** [comment]
Thanks for your reply, @thorstenMueller! Then I will gladly wait until the new models are released. I'm already very excited - the "new" Thorsten model sounds highly natural! Wow!

**Comment by Mareike-RTY** [comment]
Dear Thorsten, 

I have just tested your newly released VITS model on the TTS server, and the generated audios really sound amazing! Great work, thank you.
I found out that the new model is in the same format (`data.pkl`) as the previous one, so unfortunately, I cannot resolve my original thread on my own because I do not know how to use this kind of model instead of a `.h5` model for finetuning.

Would you please be so kind to answer my original question and provide me maybe with a little information of how I could proceed?
Thank you very much in advance!

Have a nice weekend.

**Comment by Mareike-RTY** [comment]
Dear Thorsten,

in order to hopefully solve the unpickling error mentioned above, maybe you could let me know how you pickled the VITS model and which Python version was used? I have read a post saying "if the model is not unpickled the same way it was pickled, unpickling cannot work". 

Thank you very much, and have a nice day.

**Comment by Mareike-RTY** [comment]
Update: In the meantime I started using coquiTTS instead of TensorFlowTTS for finetuning the VITS model. 
Now it's working, so I guess this issue can be closed.

**Comment by domcross** [comment]
> in order to hopefully solve the unpickling error mentioned above, maybe you could let me know how you pickled the VITS model and which Python version was used? I have read a post saying "if the model is not unpickled the same way it was pickled, unpickling cannot work".

@Mareike-RTY The model was trained in a Python 3.6 environment.
