### ISSUE TITLE
Question with Phonemes

### ISSUE THREAD

**Issue by AliNGatGeeks** [thorstenMueller/Thorsten-Voice#36]
Hi Thorsten. 
I have a question about tokenization based on phonemes ! I know this is not related to this repo but I would appreciate any help. 
I have used your dataset and produced German text to speech with your dataset using Tacotron 2 + MEL GAN  and it sounds great thanks to your dataset. 
Now I want to try phoneme instead of characters for tokenization and sadly I don't have any knowledge on that. I have used the e-speak package to generate the tokens and it has resulted in the following list of phonemes:

![phonemes](https://user-images.githubusercontent.com/96764993/172372488-dc86a043-a4ff-474b-bdee-7c70147ed821.png)

do you have any Idea if this many phonemes looks right? I   have used the espeak-ng package for this process! 
https://github.com/espeak-ng/espeak-ng
and If (and presumably) I am off way track! do you a resource I can read for this tokenization?

**Comment by thorstenMueller** [comment]
Hi @AliNGatGeeks ,
thanks for your nice feedback on my dataset.

Did you train a phoneme based model? It should work with normal text input instead of phoneme input.

**Comment by AliNGatGeeks** [comment]
Hello

I did and I get this list as the result. I did train with characters and the output is very nice (at least I think it is :) ). I just wanted to see how much difference I get with phonemes.

**Comment by thorstenMueller** [comment]
When you're using Coqui TTS there's no need to compute phonemes by yourself. Setting `use_phonemes=True` and `phoneme_language="de"` should be enough.
https://tts.readthedocs.io/en/latest/tutorial_for_nervous_beginners.html?highlight=use_phonemes

**Comment by AliNGatGeeks** [comment]
Ah ... ok :) I will try that. Thank you for your response. I will try that.
