### ISSUE TITLE
Documenting the process of building an open voice model out of audio files

### ISSUE THREAD

**Issue by sandreas** [thorstenMueller/Thorsten-Voice#37]
Hey Thorsten,

thank you for this project. Really promising and impressive.

I did not find a detailed documentation or guide of the process you are going through to build a TTS model... I mean:

- Setting up an environment
- recording audio
- optimizing audio (like Dominik does)
- Putting (my own) audio recordings and transcriptions to the right place
- Generating and training a TTS model
- Using the model to generate speech / audio files from existing text

Maybe you could give a short overview or at least some links on how your training process is set up and used in development? 

I'm asking because I have a huge set of my own voice from an ongoing private project and now I would like to use this to train a model for reading audio books for my little daughter. How would I do that?

Maybe this would be possible also for other existing audio sets if I knw how to prepare them and what to do to make them "compatible" with your process... Take for example https://vorleser.net - all it would take is a little `ffmpeg` magic and some transcription effort to choose between a wide variety of trained voice models. There is also librivox or deepspeech (e.g. https://github.com/AASHISHAG/deepspeech-german). For computing power I would probably use Google Scholar, which is free under some circumstances...

What do you think?

**Comment by thorstenMueller** [comment]
Hi @sandreas ,
thanks for your feedback and ideas.

Do you know the tutorials on my Youtube channel. There's an english video and a small serien of german videos that show the process on how to create your own TTS voice.

English: https://www.youtube.com/watch?v=4YT8WZT_x48&t=1s
German playlist: https://www.youtube.com/watch?v=jZrsz_3j16c&list=PL19C7uchWZeo-j9mUmYeVfgzbP3vHSHU-

**Comment by sandreas** [comment]
@thorstenMueller 

>  thanks for your feedback and ideas.
You're welcome! :-)

> Do you know the tutorials on my Youtube channel. There's an english video and a small serien of german videos that show the process on how to create your own TTS voice.

I did not know that this was about the latest tech but thank you for clarifying this... I'll take a look. Really appreciate it!
