### ISSUE TITLE
Eigene TTS erstellen

### ISSUE THREAD

**Issue by Johnnii360** [thorstenMueller/Thorsten-Voice#40]
Hi Thorsten!

Leider finde ich sonst keine mir möglich Kontaktform, um Dich anzuschreiben. Ich würde evtl. auch gerne sowas machen, allerdings z.B. in Bayrisch oder Fränkisch. Wie macht man sowas?

LG
Johannes

**Comment by Johnnii360** [comment]
Upis, das hatte ich ganz übersehen. Hatte nur die Links bei Kontakt gesehen. Aber danke Dir für das Video!

**Comment by thorstenMueller** [comment]
Guter Hinweis von Dir. Das mit dem Kontaktformular war nicht wirklich intuitiv. Ich habe es angepasst.
<img width="254" alt="Thorsten-Voice Kontaktformular" src="https://user-images.githubusercontent.com/9558265/186498038-cafe6b92-0356-4f3c-a260-245173a57956.png">
