### ISSUE TITLE
44khz 16 bit available?

### ISSUE THREAD

**Issue by rafaelvalle** [thorstenMueller/Thorsten-Voice#41]
first of all, thank you so much for making this data available!
would it be possible to share the 44khz 16 bit data?

**Comment by thorstenMueller** [comment]
Hi @rafaelvalle and thanks for your kind feedback 😊.
Currently there are no plans on releasing the dataset in higher samplerates.

**Comment by rafaelvalle** [comment]
echt? schade! :)
