### ISSUE TITLE
Source of Text Prompts

### ISSUE THREAD

**Issue by liaeh** [thorstenMueller/Thorsten-Voice#42]
Hi, great work and great project! 👍 

I am interested in how you curated the text prompts for the recordings in your dataset. For example, from where did you source the prompts? Did you collect prompts from multiple domains? Did you select all the prompts you found in a source, a random subset, or did you filter some out in a pre-processing step? 

Thanks for any hints! Much appreciated.

**Comment by thorstenMueller** [comment]
Hi, thanks for your nice feedback 😊.
I've taken most phrases from Mozilla Common Voice ([Sentence Collector](https://raw.githubusercontent.com/mozilla/voice-web/master/server/data/de/sentence-collector.txt)). I hope this helps you.
