### ISSUE TITLE
Help for vocoder training for Coqui

### ISSUE THREAD

**Issue by nfaraji2002** [thorstenMueller/Thorsten-Voice#43]
Hi 
I am wondering if I have to train a vocoder for a new language (a new trained TTS) in Mozilla TTS. How can I find a documentation for vocoder training?

Thanks,
Neda

**Comment by thorstenMueller** [comment]
Hi,
training a VITS model might be an alternative, because the vocoder is included there. So no need to train a special vocoder manually.

**Comment by nfaraji2002** [comment]
Thanks for your reply.
I want to train TTS for Persian language. How many sentences are required for good training? And how can I define the characters of a special language? 
In which cases do I have to train the vocoder too?
I would be grateful if you can show me a roadmap.

**Comment by thorstenMueller** [comment]
More recorded sentences -> better and more natural TTS result :-). You can try it with (eg. 1000 sentences) and listen to the result and add more phrases on demand.
Try using VITS TTS model, because there's no need for an extra vocoder. Are you planning to train with phonemes or characters?

Do you know my Youtube channel / video on voice tech / cloning?
https://youtu.be/4YT8WZT_x48

**Comment by nfaraji2002** [comment]
Thanks for the reply. Actually, we have 1000 sentences at the moment and we are training the model based on your Tactron2-DDC recipe, with a small change in configuration such as scheduling learning rate and etc. 

We have set these parameters:
 "use_phonemes": true,
  "phonemizer": "espeak",
  "phoneme_language": "fa"
and the training is with phonemes.

We want to finally test our trained TTS model on Raspberry PI 4, but we don't know how to convert the model to a small one (the current model is 576 MB), so that it can be executed on a weak-processing board. We have tried to use ONNX for model conversion, but it seems to be complicated and we were not successful at conversion. Do you have any experience in this regard?

Is there any more powerful mini-computer for running TTS or STT models, in real-time?

**Comment by thorstenMueller** [comment]
Maybe you can check [Larynx2](https://github.com/rhasspy/larynx2/) for performant TTS implementation using ONNX and Raspberry Pi.

**Comment by thorstenMueller** [comment]
I'll close this issue for the moment. But feel free to reopen it when you've further questions.
