### ISSUE TITLE
Multispeaker-Finetuning on Single-Speaker-VITS-Model

### ISSUE THREAD

**Issue by jtotheakob** [thorstenMueller/Thorsten-Voice#44]
Hi Thorsten, 

ich bin gerade dabei die Welt von TTS zu entdecken und bin dabei auf deinen genialen Beitrag für die deutsche Stimme gestoßen! Jetzt habe ich auch schon ein bisschen damit rumgespielt und mit einem kleinen Datensatz meiner Stimme dein VITS Model zu einem sehr guten Ergebnis gebracht. In einem nächsten Schritt habe ich eine zweite Stimme hinzugefügt und somit ein Multispeaker-Model aus deinem VITS Model trainiert. Das hat zwar einigermaßen geklappt, jedoch ist das Ergebnis der Stimmen schlechter, als beim Finetuning der Einzelstimmen. Jetzt hier meine Frage: Gibt es eine Möglichkeit, durch ein Multispeaker-Finetuning die gleiche bzw. eine sogar bessere Qualität (da größerer Datensatz von zwei Sprechern) zu erhalten?
Ich wäre dir um deine Hilfe sehr dankbar!

BG
Jakob

**Comment by thorstenMueller** [comment]
Hallo Jakob,
vielen Dank für dein großes Lob 😊.
Da ich mit dem Trainieren von Multispeaker Modellen keine praktische Erfahrung habe kann ich dir vermutlich nicht wirklich gut weiterhelfen. Eventuell fragst Du in der Coqui TTS Community an. Da solltest Du kompetente Hilfe bekommen.
https://github.com/coqui-ai/TTS/discussions

**Comment by jtotheakob** [comment]
Vielen Dank für deine rasche Rückmeldung. Das werde ich doch gleich mal versuchen.
Solltest du mal wieder ein Video planen, so würde mich das Thema Trainingsauswertung mithilfe von Tensorboard sehr interessieren. ;)
