### ISSUE TITLE
training duration / female voice?

### ISSUE THREAD

**Issue by gnmarten** [thorstenMueller/Thorsten-Voice#46]
thanks so much for your voice and your Youtube explanation videos, you really got me into to this stuff

now I have some specific questions: 
- how many hours of training is recommended for training on e.g. 4000 wav samples. I'm currently capped at 8 hours, and resulting voice models are either too low or too high voiced, but otherwise sounding OK (when adjusted in Audition). Will pitch improve with longer training?
- would it be possible to finetune a female dataset on your (male) model and achieve convincing results (i.e. a woman voice)?
- if so, what are recommended settings (I've only found a reference to Melotron as relevant so far)

Thanks in advance and keep rocking

BTW, I recommend this Whisperer repository for creating the dataset in one go: https://github.com/miguelvalente/whisperer

**Comment by thorstenMueller** [comment]
Hi @gnmarten ,
thanks for your nice feedback 🙂. 

- IMHO pitch will not change significant with more training steps. Maybe use Coqui TTS jupyter notebooks to check your dataset if there are recordings that have a too high variance and filter out these recordings before starting training (https://github.com/coqui-ai/TTS/tree/dev/notebooks).
- Not sure if this works, as i've no experience on finetuning with another gender.

Thanks for the "Whisper" link, i'll check it out (when i hopefully find some time for it).

**Comment by thorstenMueller** [comment]
I'll close this issue, but feel free to reopen it in case of further questions.
