### ISSUE TITLE
Windows: tts_to_file ignoring German Umlauts

### ISSUE THREAD

**Issue by TaskManager91** [thorstenMueller/Thorsten-Voice#50]
Hi, when I call the tts_to_file function in Thorsten tacotron2-DDC on Windows, it seems that Coqui-TTS is ignoring the German umlauts:

```
from TTS.api import TTS

tts_model = TTS(model_name="tts_models/de/thorsten/tacotron2-DDC", gpu=True)
tts_model.tts_to_file("Öffentliche trübe Tragödie", file_path="voice_bot.wav")
```
The resulting wave file, skips the included umlauts.
According to the console output, the string is displayed correctly (no encoding issues):

```
 > tts_models/de/thorsten/tacotron2-DDC is already downloaded.
 > vocoder_models/de/thorsten/hifigan_v1 is already downloaded.
...
 > Text splitted to sentences.
['Öffentliche trübe Tragödie']
```

The issue only occurs on Windows. However, when using a different German model e.g., `tts_model = TTS("tts_models/deu/fairseq/vits", gpu=True)` it works fine. Furthermore, the Fairseq model explicitly outputs the vocabulary beforehand, where the German umlauts are also included:
```
 > tts_models/deu/fairseq/vits is already downloaded.
 > Setting up Audio Processor...
....
[' ', 'v', '2', 'q', 'g', '-', 'f', '1', '8', 'a', 'h', '4', 'ö', '3', 'r', 'm', 'ä', 'l', 'n', 't', 'ë', 'd', 'b', 'y', 'ß', 'o', 'u', '_', 'j', 's', '6', '5', 'ï', 'c', 'i', 'ü', 'p', 'k', 'e', '–', 'w', 'z', '7', 'x', '0']
 > Text splitted to sentences.
['Öffentliche trübe Tragödie']
```

**Comment by thorstenMueller** [comment]
Hi, i'll try to check it soon - when sitting at my Windows machine 😉. Does it work by just running "tts" or "tts-server" and is struggling with Python integration?
Just being curious, what that "/deu/fairseq/vits" is about, as i don't see it [here](https://raw.githubusercontent.com/coqui-ai/TTS/dev/TTS/.models.json).

**Comment by TaskManager91** [comment]
Using "tts" or "tts-server" works like a charm. Only the Python Integration appears to be impacted by the issue. Unfortunately, using the command line method would reload the model each time i use it in my code, which has a significant impact on performance.

Coqui-TTS has a new Fairseq [Fairseq](https://github.com/coqui-ai/TTS#coquiai-news ) integration.

**Comment by thorstenMueller** [comment]
Hi @TaskManager91 , i can confirm the problem. I've tried your snipplet (just without gpu) on Mac OS successfully and run into the same problem on Windows.

> from TTS.api import TTS
> tts_model = TTS(model_name="tts_models/de/thorsten/tacotron2-DDC", gpu=False)
> tts_model.tts_to_file("Öffentliche trübe Tragödie", file_path="voice_bot.wav")

To check if it's not a general Windows encoding problem on my system  i've tested it with my Thorsten-VITS model. This model does not have the problem.
Maybe you can test it using this model:
> tts_models/de/thorsten/vits

The DDC model has been trained with espeak-ng and the VITS model using gruut as phonemizer. Maybe that's a problem. I'll try to figure out what might be the problem.
