### ISSUE TITLE
Voz Português Brazil

### ISSUE THREAD

**Issue by gersooonn** [thorstenMueller/Thorsten-Voice#52]
Hi, how are you?

Could you use this voice to train a voice for Portuguese on coqui.ai? We in Brazil don't have it, we only have it for Portugal, the pronunciation is very different. There is this model TTS-Portuguese Corpus https://github.com/Edresson/TTS-Portuguese-Corpus
He has already trained in Portuguese, but I don't know how to put it in coqui.ai to be able to use it.

**Comment by thorstenMueller** [comment]
Hi, i'm fine thanks for asking. Hope you're doing well too 😊.
If there isn't already a brazilian Coqui TTS model available i would be better if it's trained by a native speaker who can validate the models quality. As Edresson is active on Coqui TTS community (imho, he's part of Coqui) maybe it's better to discuss this topic there. But technically this should be possible based on the dataset you've mentioned.

https://github.com/coqui-ai/TTS/discussions
