### ISSUE TITLE
Voice synthesizing fails after finetuning

### ISSUE THREAD

**Issue by jtotheakob** [thorstenMueller/Thorsten-Voice#54]
Hi Thorsten, 

I've got a question concerning finetuning of a voice. I have finetuned a couple of voices in the past based on your german vits model. It has always worked perfectly fine. However, now I'm trying to finetune my own voice. I haven't changed any of the settings, but just changed the dataset. The dataset has roughly the same size and content as previous datasets, that I used for finetuning. After training of around 5000 steps the sound of the voice is great. But for some reason, coqui does not synthesize the text I input correctly. The resulting audio is just some gibberish that sounds like my voice but is nowhere near the text I wanted to have. Do you by any chance know what I could improve or change, or did you have similar problems in the past? The other voices I've trained do work perfectly, so I'm totally stuck and could really use some help. In case you need any files to better understand the problem please let me know. 

Thanks a lot in advance!
Jakob

**Comment by thorstenMueller** [comment]
Is your dataset, you use for finetuning, the same sample rate like mine?
As i have no practical experience with finetuning yet it might be a good idea to ask this question on Coqui TTS GitHub discussion as there are some finetuning experts that could have some good ideas.

**Comment by thorstenMueller** [comment]
I close this issue now, but feel free to reopen it if problem still exists. Of course you can share your solution, too if you got it fixed.
