### ISSUE TITLE
Das Wort "Prolog" führt zu Decoder stopped with `max_decoder_steps` 

### ISSUE THREAD

**Issue by cm7695** [thorstenMueller/Thorsten-Voice#55]
Hallo Herr Müller,

das Wort "Prolog" erzeugt den Fehler Decoder stopped with `max_decoder_steps`. Selbst eine Erhöhung auf 4000 führt ebenfalls zu dem Fehler. (Version TTS 0.17.4)
Erzeugt wurd eine Audiodatei mittels 
tts --text "Prolog" --model_name tts_models/de/thorsten/tacotron2-DDC --out_path test1.wav

Die Audiodatei ist relativ lang und nach dem Wort Prolog sind fragmente zu hören.

Audiodatei
https://github.com/thorstenMueller/Thorsten-Voice/assets/22102973/bf4caaaf-eee9-4d3d-a5f0-e70a7bff9874
Die Textausgabe des Befehls:
tts --text "Prolog" --model_name tts_models/de/thorsten/tacotron2-DDC --out_path test1.wav
 > tts_models/de/thorsten/tacotron2-DDC is already downloaded.
 > vocoder_models/de/thorsten/hifigan_v1 is already downloaded.
 > Using model: tacotron2
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:None
 | > pitch_fmin:0.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Model's reduction rate `r` is set to: 2
 > Vocoder Model: hifigan
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:None
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:/home/user/.local/share/tts/vocoder_models--de--thorsten--hifigan_v1/scale_stats.npy
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > Generator Model: hifigan_generator
 > Discriminator Model: hifigan_discriminator
Removing weight norm...
 > Text: Prolog
 > Text splitted to sentences.
['Prolog']
   > Decoder stopped with `max_decoder_steps` 4000
 > Processing time: 200.3763484954834
 > Real-time factor: 2.144222194124611
 > Saving output to test1.wav

**Comment by thorstenMueller** [comment]
Hallo,
dieses Verhalten sollte sich sehr leicht lösen lassen. Einfach einen Punkt ans Ende setzen (also: "Prolog."). Ohne ein entsprechendes Ende weiß das Modell nicht, dass der Satz endet und es generiert so lange "random" Audio bis die max_decoder_steps erreicht werden.

**Comment by cm7695** [comment]
Vielen Dank für ihre Hilfe. Das Setzen des Punktes funktioniert wie gewünscht.

Und an dieser Stelle auch recht herzlichen Dank für das Erstellen der Stimme. Ich bin wirklich begeistert, was die Natürlichkeit des Klangbildes der Stimme angeht und habe  großen Respekt vor der Arbeit die dahinter steckt.
