### ISSUE TITLE
Issue installing requirements.txt - No matching distribution found for piper-phonemize~=1.1.0

### ISSUE THREAD

**Issue by kerwinkfs** [thorstenMueller/Thorsten-Voice#57]
I followed the directions and when trying to install the requirements I got this error - No matching distribution found for piper-phonemize~=1.1.0.

Any help will be appreciated. 

Thanks,

**Comment by kerwinkfs** [comment]
Package    Version
---------- -------
This is the env list from running the command - pip list.

pip        23.3.1
setuptools 68.0.0
wheel      0.41.0

Thanks,

**Comment by thorstenMueller** [comment]
Maybe you can try installing it with "pip install piper-phonemize==1.1.0". A package in this version is available and should be installable.
https://pypi.org/project/piper-phonemize/

**Comment by thorstenMueller** [comment]
I'll close this issue. Please feel to reopen it, if not fixed yet.
