### ISSUE TITLE
IPv6 issue

### ISSUE THREAD

**Issue by street-grease-coder** [thorstenMueller/Thorsten-Voice#58]
I cannot access the Thorsten Voice demo in LAN beause of, probably, ipv6 issues:

INFO:werkzeug: * Running on http://[::1]:5002/ (Press CTRL+C to quit)

I don't know how the tts-server works, but it would be great if we could specify --host 0.0.0.0 instead of just the --port.

How would I achieve that? 

Thanks for this enormous piece of work

**Comment by thorstenMueller** [comment]
I have no practical experience with IPv6 by now, but i just tried running the Coqui TTS server. As you said there's no --host argument that can be set. But when i start the TTS server it binds locally to an IPv6 adress and is available by calling the IPv4 address in the browser.
Do you try opening the IPv6 or IPv4 url?

And - you're welcome 😊.

**Comment by street-grease-coder** [comment]
worked, simply had typed wrong ipv4 address, closing!
