### ISSUE TITLE
GlowTTs

### ISSUE THREAD

**Issue by Hafiz-ATHAR** [thorstenMueller/Thorsten-Voice#61]
Guude!
I would like to start by saying
thank you so much for putting alot of effort in creating wonderful datasets. 
I tried your VITS and Tacotron2 models from coqui. The output is very promising. 
I even fine-tuned your VITS model and it shows alot of promise. 
I wanted to ask you , have you ever trained a Glow-TTS model using coqui implementation ?
On Coqui github page i only see Vits and Tacotron2.

**Comment by thorstenMueller** [comment]
Guude and sorry for late response! No, i haven't trained a Coqui Glow-TTS on my dataset.

**Comment by Hafiz-ATHAR** [comment]
Okay, thank you for replying.
