### ISSUE TITLE
wird es eine app für android auf fdroid geben?

### ISSUE THREAD

**Issue by Mannshoch** [thorstenMueller/Thorsten-Voice#63]
Wird es die App auf fdroid geben? Ich könnte das umter Lineageos gut brauchen da fehlt eine tts app.

**Comment by thorstenMueller** [comment]
Wenn, bzw. falls es einen Piper TTS Implementierung für Android gibt, dann werden meine Thorsten-Voice Stimmen dort auch verfügbar sein. Allerdings kenne ich die Roadmap dazu nicht.

**Comment by thorstenMueller** [comment]
Ich schließe hier mal. Falls es bezüglich Piper und Android was neues gibt, können wir hier gerne weiter diskutieren.

**Comment by Mannshoch** [comment]
Wie wahrscheinlich ist es, dass die stimmen in https://github.com/espeak-ng/espeak-ng  landen?
