### ISSUE TITLE
How to properly read english words in german sentences?

### ISSUE THREAD

**Issue by GithubAnon0000** [thorstenMueller/Thorsten-Voice#67]
First of all thank you for your voice contribution!

I used  your [download instructions](https://www.thorsten-voice.de/kostenloses-deutsches-text-to-speech-tts/) and installed piper with the thorsten (high) voice.

I know I can run it like so: 
```shell
echo "In einem Computer gibt es verschiedene Komponenten. Eine dieser Komponenten ist die central processing unit, welche als CPU abgekürzt wird." | ./piper --quiet --model ./de_DE-thorsten-high.onnx --output-file ../OUTPUT/cpu.wav
``` 
It does work but the english words are mispronounced. See [cpu.zip](https://github.com/user-attachments/files/16554049/cpu.zip).

I think you mentioned somewhere that espeak-ng supports "`<en>english word</en>`" but I cannot figure out how to use your voice with espeak-ng.

My use case is that I generate .wav audio files based on strings in a libreoffice calc document, which will be imported into anki afterwards. I wrote a working script to automate all that but cannot figure out how to use english pronounciation for english words inside german sentences.

# Steps to reproduce

1.  Use the above command (or use any other string that contains english words).
2. Listen to audio.

# Version info
piper: 1.2.0
OS: Debian oldstable (gnome 3.38.5, X11)
python: 3.9.2

**Comment by thorstenMueller** [comment]
I'm happy you could solve the pronounciation issue by adjusting eSpeak dictionary (with help of my videos) 😊. It is really way better after your adjustment.

And thanks a lot for your amazing feedback on my voice contribution - happy to hear it's useful 🥰.
