### ISSUE TITLE
Normalize Dataset to -24dB

### ISSUE THREAD

**Issue by thorstenMueller** [thorstenMueller/Thorsten-Voice#7]
Due different volume levels in original recordings, these should be normalized. After chatting with @domcross and @el-tocino -24dB should be the right value for the dataset.

**Comment by tugstugi** [comment]
@thorstenMueller which tool was used for the normalization?

**Comment by domcross** [comment]
@tugstugi I have used [pyloudnorm](https://github.com/csteinmetz1/pyloudnorm) for loudness normalization
