### ISSUE TITLE
Trying to follow guide for Piper Training but running into Python issues

### ISSUE THREAD

**Issue by TheStigh** [thorstenMueller/Thorsten-Voice#70]
Hi Thorsten, was suppose to follow your video for setting up Piper Training but ran into a problem quite early.

First: 
Ubuntu 20.04.3 LTS
Default Python 3.8.10

When running the `pip3 install -e .` I run into this following error: 

`ERROR: Could not find a version that satisfies the requirement piper-phonemize~=1.1.0 (from piper-train) (from versions: none)
ERROR: No matching distribution found for piper-phonemize~=1.1.0`

Seems I need Python 3.9?

So I did another install `sudo apt install python3.9` with according `sudo apt install python3.9-dev`

Then I get a new error trying to set up the venv environment:

`stigh@ubuntu:~/piper$ python3.9 -m venv .venv
Error: Command '['/home/stigh/piper/.venv/bin/python3.9', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
`

Seems I need to have 3.8 installed as it is part of Ubuntu 20.04.3, so now I'm stuck. Any ideas how I can get around this to avoid updating to Ubunto 22.04 LTS ?

**Comment by TheStigh** [comment]
Resolved it myself, installed Python 3.10 and downgraded pip to 24.1 then I ran the venv with Python 3.10 and not Ubuntu default 3.8.

**Comment by thorstenMueller** [comment]
Happy you could solve the issue @TheStigh and thanks for sharing your solution here 😊.
